import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Playfair_Display,
  Poppins,
  Raleway,
  Lato,
  Montserrat,
  Quicksand,
  Abril_Fatface,
  Merriweather,
  Nunito,
} from "next/font/google";

import "./globals.css";
import { AppContextProvider } from "@/contexts/AppContext";

// Existing fonts
const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

// Extra heading fonts
const playfair = Playfair_Display({ variable: "--font-playfair", subsets: ["latin"], weight: ["400", "700"] });
const abril = Abril_Fatface({ variable: "--font-abril", subsets: ["latin"], weight: ["400"] });
const raleway = Raleway({ variable: "--font-raleway", subsets: ["latin"], weight: ["400", "700"] });

// Extra body fonts
const poppins = Poppins({ variable: "--font-poppins", subsets: ["latin"], weight: ["400", "600"] });
const lato = Lato({ variable: "--font-lato", subsets: ["latin"], weight: ["400", "700"] });
const montserrat = Montserrat({ variable: "--font-montserrat", subsets: ["latin"], weight: ["400", "600", "700"] });
const quicksand = Quicksand({ variable: "--font-quicksand", subsets: ["latin"], weight: ["400", "600"] });
const merriweather = Merriweather({ variable: "--font-merriweather", subsets: ["latin"], weight: ["400", "700"] });
const nunito = Nunito({ variable: "--font-nunito", subsets: ["latin"], weight: ["400", "600"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`
          ${geistSans.variable} 
          ${geistMono.variable} 
          ${playfair.variable} 
          ${abril.variable} 
          ${raleway.variable} 
          ${poppins.variable} 
          ${lato.variable} 
          ${montserrat.variable} 
          ${quicksand.variable} 
          ${merriweather.variable} 
          ${nunito.variable} 
          antialiased
        `}
      >
        <AppContextProvider> {children}</AppContextProvider>

      </body>
    </html>
  );
}
